spring:
  application:
    name: mailing-service

  datasource:
    url: jdbc:postgresql://localhost:5432/scheduler?stringtype=unspecified
    username: postgres
    password: mysecretpassword

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        default_schema: scheduler

  jackson:
    serialization:
      write_dates_as_timestamps: false
    default-property-inclusion: non_null

  liquibase:
    change-log: classpath:/db.changelog/db.changelog-master.yaml
    enabled: true

feign.client.config.default:
  connectTimeout: 160000000
  readTimeout: 160000000

server:
  port: 8096
  error:
    include-message: always

logging:
  file:
    name: mailing-service.log

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

